using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using RadialLauncher.Services.Themes;
using Serilog;

namespace RadialLauncher.Services.Localization
{
    public class LocalizationService : ILocalizationService
    {
        private static readonly string SettingsPath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "RadialLauncher", "settings.json");

        private static LocalizationService? _instance;
        public static LocalizationService Instance => _instance ??= new LocalizationService();

        private string _currentLanguage = "en";
        public string CurrentLanguage => _currentLanguage;

        public event Action? OnLanguageChanged;

        public IReadOnlyList<LanguageOption> SupportedLanguages { get; } = new List<LanguageOption>
        {
            new("de", "Deutsch (German)", "Deutsch", "🇩🇪"),
            new("en", "English (English)", "English", "🇺🇸"),
            new("es", "Español (Spanish)", "Español", "🇪🇸"),
            new("fr", "Français (French)", "Français", "🇫🇷"),
            new("it", "Italiano (Italian)", "Italiano", "🇮🇹"),
            new("ja", "Japanese (日本語)", "日本語", "🇯🇵"),
            new("ko", "Korean (한국어)", "한국어", "🇰🇷"),
            new("pl", "Polski (Polish)", "Polski", "🇵🇱"),
            new("pt-BR", "Português (Brasil)", "Português (Brasil)", "🇧🇷"),
            new("ru", "Russian (Русский)", "Русский", "🇷🇺"),
            new("tr", "Türkçe (Turkish)", "Türkçe", "🇹🇷")
        }.OrderBy(x => x.DisplayName).ToList();

        private readonly Dictionary<string, Dictionary<string, string>> _translations = new();

        public LocalizationService()
        {
            InitializeTranslations();
            LoadLanguagePreference();
        }

        public string this[string key] => GetString(key);

        public string GetString(string key, string? fallback = null)
        {
            if (_translations.TryGetValue(_currentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            {
                return val;
            }
            if (_currentLanguage != "en" && _translations.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enVal))
            {
                return enVal;
            }
            return fallback ?? key;
        }

        public void SetLanguage(string languageCode)
        {
            if (string.IsNullOrWhiteSpace(languageCode)) return;
            var match = SupportedLanguages.FirstOrDefault(l => l.Code.Equals(languageCode, StringComparison.OrdinalIgnoreCase));
            if (match == null) match = SupportedLanguages.FirstOrDefault(l => l.Code == "en") ?? SupportedLanguages.First();

            _currentLanguage = match.Code;
            SaveLanguagePreference(_currentLanguage);
            Log.Information("Language set to: {Lang}", _currentLanguage);
            OnLanguageChanged?.Invoke();
        }

        private void LoadLanguagePreference()
        {
            try
            {
                if (File.Exists(SettingsPath))
                {
                    string json = File.ReadAllText(SettingsPath);
                    using var doc = JsonDocument.Parse(json);
                    if (doc.RootElement.TryGetProperty("Language", out var langProp))
                    {
                        string? savedLang = langProp.GetString();
                        if (!string.IsNullOrEmpty(savedLang) && SupportedLanguages.Any(l => l.Code.Equals(savedLang, StringComparison.OrdinalIgnoreCase)))
                        {
                            _currentLanguage = savedLang;
                            return;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Log.Warning(ex, "Failed to load language preference from settings.json");
            }
            _currentLanguage = "en";
        }

        private void SaveLanguagePreference(string langCode)
        {
            try
            {
                if (File.Exists(SettingsPath))
                {
                    string json = File.ReadAllText(SettingsPath);
                    var dict = JsonSerializer.Deserialize<Dictionary<string, object>>(json) ?? new();
                    dict["Language"] = langCode;
                    string updatedJson = JsonSerializer.Serialize(dict, new JsonSerializerOptions { WriteIndented = true });
                    File.WriteAllText(SettingsPath, updatedJson);
                }
            }
            catch (Exception ex)
            {
                Log.Warning(ex, "Failed to save language preference to settings.json");
            }
        }

        private void InitializeTranslations()
        {
            _translations["en"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Settings & Management",
                ["Nav_Apps"] = "📋  Applications & Shortcuts",
                ["Nav_Themes"] = "🎨  Themes & Appearance",
                ["Nav_Shortcuts"] = "⚙️  Shortcuts & Startup",
                ["Nav_Backups"] = "💾  Backup & Data",
                ["Nav_System"] = "ℹ️  System & Diagnostics",

                ["Tab1_Title"] = "Application & Shortcut Management",
                ["Tab1_Sub"] = "Manage all apps, games, websites, and folders listed in the radial menu.",
                ["Scan_PC"] = "🔍 Scan PC",
                ["Add_Item"] = "➕ Add New Item",
                ["Category"] = "Category:",
                ["All_Categories"] = "All Categories",
                ["Search"] = "Search:",
                ["Search_Placeholder"] = "Search apps, games, actions...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Order",
                ["Col_Icon"] = "Icon",
                ["Col_Name"] = "Name",
                ["Col_Type"] = "Type",
                ["Col_Category"] = "Category",
                ["Col_Launches"] = "Launches",
                ["Col_Target"] = "Target",
                ["Col_Actions"] = "Actions",

                ["Tab2_Title"] = "Themes & Visual Customization",
                ["Tab2_Sub"] = "Select from 8 curated themes, customize radial opacity and density.",
                ["Themes_Header"] = "Curated Themes (8 Themes)",
                ["Preview_Header"] = "Live Radial Preview",
                ["Opacity_Title"] = "Radial Menu Opacity",
                ["Opacity_Desc"] = "Adjust background transparency level of the circular overlay.",
                ["Density_Title"] = "Ring Density Mode",
                ["Density_Desc"] = "Number of items displayed per circular ring page.",
                ["Density_Expanded"] = "Expanded (15 Items)",
                ["Density_Compact"] = "Compact (18 Items)",
                ["Access_Title"] = "Accessibility & Performance",
                ["Access_Sub"] = "Reduce motion and simplify animations for low-spec systems.",
                ["Reduce_Motion"] = "Reduce Motion / Simplified Animations",
                ["Palette_Title"] = "Active Theme Color Palette",
                ["Primary_Accent"] = "Primary Accent",
                ["Secondary_Accent"] = "Secondary Accent",
                ["Background"] = "Background",
                ["Icon_Bubble"] = "Icon Bubble",

                ["Tab3_Title"] = "Trigger Shortcut & Startup",
                ["Tab3_Sub"] = "Set the mouse button or keyboard shortcut to open the radial menu.",
                ["Trigger_Title"] = "Menu Activation Shortcut",
                ["Trigger_Desc"] = "Select a mouse button or keyboard hotkey to summon Radial Launcher.",
                ["Assign_Shortcut"] = "🎯 Assign Custom Shortcut",
                ["Startup_Title"] = "Windows Startup",
                ["Startup_Check"] = "Automatically start Radial Launcher in tray on Windows startup",
                ["Behavior_Title"] = "🎯 Menu Behavior & Navigation Guidelines",
                ["Behavior_Body"] = "• Auto-Close: Menu closes automatically when cursor moves 330px away.\n• Global Navigation: Drag with middle-mouse or use scroll wheel to switch pages/categories.\n• Quick Actions: Hovering items reveals instant actions at the center.",

                ["Tab4_Title"] = "Backup & Data Management",
                ["Tab4_Sub"] = "Safely backup and restore your shortcuts, stats, and theme settings.",
                ["LocalBackup_Title"] = "💾 Local Disk Backup & Restore",
                ["LocalBackup_Sub"] = "Automatically or manually backup shortcuts, categories, and settings to local storage. Last 10 backups are preserved.",
                ["Backup_Now"] = "💾 Create Local Backup",
                ["Restore_Backup"] = "📂 Restore from Backup",
                ["JsonBackup_Title"] = "📤 JSON Export / Import",
                ["JsonBackup_Sub"] = "Export or import your complete configuration and shortcuts as a JSON file.",
                ["Export"] = "📤 Export (JSON)",
                ["Import"] = "📥 Import (JSON)",

                ["Tab5_Title"] = "Updates & Diagnostics",
                ["Tab5_Sub"] = "System diagnostic logs, error logs, and application updates.",
                ["Language"] = "🌐 Display Language",
                ["Language_Desc"] = "Select language for application UI and radial menu (Default: English). Sorted alphabetically.",
                ["Updates_Title"] = "🚀 Application Updates",
                ["Installed_Version"] = "Installed Version: v1.0.0 (Final Release)",
                ["AutoCheck_Updates"] = "Automatically check for updates on startup",
                ["Check_Updates"] = "🔄 Check for Updates Now",
                ["Diag_Title"] = "📊 System Diagnostics & Logs",
                ["Diag_Sub"] = "Application logs and system diagnostic summary.",
                ["Open_Logs"] = "📁 Open Logs Folder",
                ["Copy_Diag"] = "📋 Copy Diagnostics",
                ["Reset_Title"] = "⚠️ Reset to Factory Defaults",
                ["Reset_Sub"] = "Restores all theme, shortcut, and visual settings to defaults. (User database is preserved)",
                ["Reset_Factory"] = "Reset to Factory Defaults",

                ["Status_Ready"] = "Ready.",
                ["Status_Saved"] = "Settings saved successfully.",
                ["Success"] = "Success",
                ["Error"] = "Error",
                ["Restore_Success"] = "Backup successfully restored and applied.",
                ["Restore_Confirm"] = "Restore backup '{0}'?\nThis will overwrite current items and settings.",
                ["Restore_Confirm_Title"] = "Restore Confirmation",
                ["Reset_Confirm"] = "Reset all theme, shortcut, and appearance settings to defaults?\n(Your items and usage counts will be preserved)",
                ["Reset_Confirm_Title"] = "Reset Settings",
                ["Delete_Confirm"] = "Delete '{0}'?",
                ["Delete_Confirm_Title"] = "Delete Confirmation",

                ["Play"] = "▶ Play",
                ["Store"] = "🛒 Store",
                ["Community"] = "👥 Community",
                ["Location"] = "📁 Location",
                ["Run_Admin"] = "⚡ Run as Admin",
                ["Terminal"] = "⚡ Terminal",
                ["Open"] = "Open",
                ["Copy"] = "Copy",
                ["Library"] = "Library",
                ["Launch"] = "Launch"
            };

            _translations["tr"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Yönetim & Ayarlar",
                ["Nav_Apps"] = "📋  Uygulamalar & Kısayollar",
                ["Nav_Themes"] = "🎨  Temalar & Görsellik",
                ["Nav_Shortcuts"] = "⚙️  Kısayol & Başlangıç",
                ["Nav_Backups"] = "💾  Yedekleme & Veri",
                ["Nav_System"] = "ℹ️  Güncelleme & Tanılama",

                ["Tab1_Title"] = "Uygulama & Kısayol Yönetimi",
                ["Tab1_Sub"] = "Radyal menüde listelenen tüm program, web sitesi ve klasörleri yönetin.",
                ["Scan_PC"] = "🔍 Bilgisayarı Tara",
                ["Add_Item"] = "➕ Yeni Öğe Ekle",
                ["Category"] = "Kategori:",
                ["All_Categories"] = "Tüm Kategoriler",
                ["Search"] = "Ara:",
                ["Search_Placeholder"] = "Uygulama, oyun veya eylem ara...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Sıra",
                ["Col_Icon"] = "İkon",
                ["Col_Name"] = "İsim",
                ["Col_Type"] = "Tür",
                ["Col_Category"] = "Kategori",
                ["Col_Launches"] = "Çalıştırma",
                ["Col_Target"] = "Hedef",
                ["Col_Actions"] = "İşlemler",

                ["Tab2_Title"] = "Görsel Temalar & Şeffaflık",
                ["Tab2_Sub"] = "8 seçkin renk paletinden birini seçin, radyal şeffaflığı ve yoğunluğu ayarlayın.",
                ["Themes_Header"] = "Hazır Temalar (8 Seçkin Tema)",
                ["Preview_Header"] = "Canlı Dairesel Önizleme",
                ["Opacity_Title"] = "Radial Şeffaflığı (Opacity)",
                ["Opacity_Desc"] = "Dairesel menünün arkaplan şeffaflık derecesini ayarlar.",
                ["Density_Title"] = "Halka Yoğunluğu (Density)",
                ["Density_Desc"] = "Tek bir halka sayfasında kaç öğe yerleştirileceğini belirler.",
                ["Density_Expanded"] = "Geniş (15 Öğeli)",
                ["Density_Compact"] = "Kompakt (18 Öğeli)",
                ["Access_Title"] = "Erişilebilirlik & Performans",
                ["Access_Sub"] = "Düşük donanımlarda veya sade animasyon tercihinde hareketi azaltın.",
                ["Reduce_Motion"] = "Hareketi Azalt / Animasyonları Sadeleştir (Reduce Motion)",
                ["Palette_Title"] = "Seçili Tema Renk Paleti",
                ["Primary_Accent"] = "Birincil Vurgu",
                ["Secondary_Accent"] = "İkincil Vurgu",
                ["Background"] = "Arkaplan",
                ["Icon_Bubble"] = "İkon Baloncuğu",

                ["Tab3_Title"] = "Tetikleme Kısayolu & Başlangıç",
                ["Tab3_Sub"] = "Menüyü açmak için kullanacağınız fare ve klavye kısayollarını belirleyin.",
                ["Trigger_Title"] = "Menüyü Tetikleme Kısayolu",
                ["Trigger_Desc"] = "Radial Launcher'ı ekranda açmak için farenizden veya klavyenizden bir kısayol seçin.",
                ["Assign_Shortcut"] = "🎯 Yeni Kısayol Ata",
                ["Startup_Title"] = "Windows Başlangıcı",
                ["Startup_Check"] = "Windows açıldığında Radial Launcher'ı otomatik başlat",
                ["Behavior_Title"] = "🎯 Menü Davranışı & Gezinme Kuralları",
                ["Behavior_Body"] = "• Otomatik Kapanma: Fare radyal menü alanından 330px uzaklaştığında menü otomatik kapanır.\n• Global Gezinme: Farenin orta tuşuyla basıp sağa/sola sürükleyerek veya fare tekerleğiyle sayfalar ve kategoriler arası geçebilirsiniz.\n• Hızlı Eylemler: Öğelerin üzerine fare ile gelindiğinde hızlı aksiyon kartı merkezde görüntülenir.",

                ["Tab4_Title"] = "Yedekleme & Veri Yönetimi",
                ["Tab4_Sub"] = "Kısayollarınızı, istatistiklerinizi ve tema ayarlarınızı güvenle yedekleyin.",
                ["LocalBackup_Title"] = "💾 Yerel Disk Yedekleme & Geri Yükleme",
                ["LocalBackup_Sub"] = "Tüm kısayollarınızı, kategorilerinizi ve istatistiklerinizi yerel diske otomatik veya manuel yedekleyin. Son 10 yedek güvenle korunur.",
                ["Backup_Now"] = "💾 Şimdi Yerel Yedekle",
                ["Restore_Backup"] = "📂 Yerel Yedekten Geri Yükle",
                ["JsonBackup_Title"] = "📤 JSON Dışa / İçe Aktar",
                ["JsonBackup_Sub"] = "Ayarlarınızı ve kısayollarınızı JSON dosyası olarak bilgisayarınıza kaydedin veya farklı bir cihazdan içe aktarın.",
                ["Export"] = "📤 Dışa Aktar (JSON)",
                ["Import"] = "📥 İçe Aktar (JSON)",

                ["Tab5_Title"] = "Güncellemeler & Tanılama",
                ["Tab5_Sub"] = "Sistem tanılama bilgileri, hata kayıtları ve yazılım güncellemeleri.",
                ["Language"] = "🌐 Dil Seçimi / Display Language",
                ["Language_Desc"] = "Uygulama arayüzü ve radyal menü için dil seçin (Varsayılan: English). Alfabetik olarak sıralanmıştır.",
                ["Updates_Title"] = "🚀 Yazılım Güncellemeleri",
                ["Installed_Version"] = "Yüklü Sürüm: v1.0.0 (Final Release)",
                ["AutoCheck_Updates"] = "Açılışta güncellemeleri otomatik kontrol et",
                ["Check_Updates"] = "🔄 Güncellemeleri Şimdi Kontrol Et",
                ["Diag_Title"] = "📊 Tanılama & Sistem Kayıtları",
                ["Diag_Sub"] = "Uygulama log dosyaları ve sistem tanılama bilgileri.",
                ["Open_Logs"] = "📁 Log Klasörünü Aç",
                ["Copy_Diag"] = "📋 Tanılamayı Kopyala",
                ["Reset_Title"] = "⚠️ Fabrika Ayarlarına Sıfırla",
                ["Reset_Sub"] = "Tüm tema, kısayol ve görsel ayarları varsayılan fabrika değerlerine geri döndürür. (Kullanıcı veritabanı korunur)",
                ["Reset_Factory"] = "Fabrika Ayarlarına Sıfırla",

                ["Status_Ready"] = "Hazır.",
                ["Status_Saved"] = "Ayarlar başarıyla kaydedildi.",
                ["Success"] = "Başarılı",
                ["Error"] = "Hata",
                ["Restore_Success"] = "Yedek başarıyla geri yüklendi ve uygulandı.",
                ["Restore_Confirm"] = "'{0}' yedeği geri yüklenecek.\nMevcut verilerinizin üzerine yazılacaktır. Onaylıyor musunuz?",
                ["Restore_Confirm_Title"] = "Yedekten Geri Yükleme Onayı",
                ["Reset_Confirm"] = "Tüm tema, kısayol ve görsel ayarlarınız varsayılan fabrika değerlerine sıfırlanacaktır.\n(Kullanıcı öğeleri, kısayollar ve kullanım sayaçları KORUNUR)\n\nDevam etmek istiyor musunuz?",
                ["Reset_Confirm_Title"] = "Ayarları Sıfırla",
                ["Delete_Confirm"] = "'{0}' silinsin mi?",
                ["Delete_Confirm_Title"] = "Silme Onayı",

                ["Play"] = "▶ Oyna",
                ["Store"] = "🛒 Mağaza",
                ["Community"] = "👥 Topluluk",
                ["Location"] = "📁 Konum",
                ["Run_Admin"] = "⚡ Yönetici",
                ["Terminal"] = "⚡ Terminal",
                ["Open"] = "Aç",
                ["Copy"] = "Kopyala",
                ["Library"] = "Kütüphane",
                ["Launch"] = "Başlat"
            };

            _translations["de"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Einstellungen & Verwaltung",
                ["Nav_Apps"] = "📋  Anwendungen & Verknüpfungen",
                ["Nav_Themes"] = "🎨  Designs & Aussehen",
                ["Nav_Shortcuts"] = "⚙️  Tastenkombinationen & Autostart",
                ["Nav_Backups"] = "💾  Sicherung & Daten",
                ["Nav_System"] = "ℹ️  System & Diagnose",

                ["Tab1_Title"] = "Anwendungs- & Verknüpfungsverwaltung",
                ["Tab1_Sub"] = "Verwalten Sie alle im Radialmenü aufgelisteten Programme, Websites und Ordner.",
                ["Scan_PC"] = "🔍 PC Scannen",
                ["Add_Item"] = "➕ Neues Element Hinzufügen",
                ["Category"] = "Kategorie:",
                ["All_Categories"] = "Alle Kategorien",
                ["Search"] = "Suchen:",
                ["Search_Placeholder"] = "Apps, Spiele, Aktionen suchen...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Pos",
                ["Col_Icon"] = "Symbol",
                ["Col_Name"] = "Name",
                ["Col_Type"] = "Typ",
                ["Col_Category"] = "Kategorie",
                ["Col_Launches"] = "Starts",
                ["Col_Target"] = "Ziel",
                ["Col_Actions"] = "Aktionen",

                ["Tab2_Title"] = "Designs & Visuelle Anpassung",
                ["Tab2_Sub"] = "Wählen Sie aus 8 Designs und passen Sie Transparenz und Dichte an.",
                ["Themes_Header"] = "Designs (8 Kurationen)",
                ["Preview_Header"] = "Live-Radialvorschau",
                ["Opacity_Title"] = "Radialmenü-Transparenz",
                ["Opacity_Desc"] = "Passen Sie die Hintergrundtransparenz des Menüs an.",
                ["Density_Title"] = "Ringdichte-Modus",
                ["Density_Desc"] = "Anzahl der angezeigten Elemente pro Ringseite.",
                ["Density_Expanded"] = "Erweitert (15 Elemente)",
                ["Density_Compact"] = "Kompakt (18 Elemente)",
                ["Access_Title"] = "Barrierefreiheit & Leistung",
                ["Access_Sub"] = "Reduzieren Sie Animationen für leistungsschwache Systeme.",
                ["Reduce_Motion"] = "Animationen Reduzieren",
                ["Palette_Title"] = "Farbpalette Des Aktiven Designs",
                ["Primary_Accent"] = "Primärer Akzent",
                ["Secondary_Accent"] = "Sekundärer Akzent",
                ["Background"] = "Hintergrund",
                ["Icon_Bubble"] = "Symbolblase",

                ["Tab3_Title"] = "Aktivierungs-Tastenkombination & Autostart",
                ["Tab3_Sub"] = "Wählen Sie Maus- oder Tastaturbefehle zum Öffnen des Menüs.",
                ["Trigger_Title"] = "Aktivierungs-Tastenkombination",
                ["Trigger_Desc"] = "Wählen Sie die Maus- oder Tastaturtaste zum Öffnen des Radialmenüs.",
                ["Assign_Shortcut"] = "🎯 Benutzerdefinierte Tastenkombination",
                ["Startup_Title"] = "Windows-Autostart",
                ["Startup_Check"] = "Radial Launcher beim Windows-Start automatisch im Infobereich ausführen",
                ["Behavior_Title"] = "🎯 Menüverhalten & Navigation",
                ["Behavior_Body"] = "• Automatisches Schließen: Menü schließt bei 330px Mausabstand.\n• Navigation: Mittlere Maustaste gedrückt halten oder Mausrad nutzen.\n• Schnellaktionen: Bewegen Sie den Mauszeiger über Symbole.",

                ["Tab4_Title"] = "Sicherung & Datenverwaltung",
                ["Tab4_Sub"] = "Sichern Sie Verknüpfungen, Statistiken und Designeinstellungen sicher.",
                ["LocalBackup_Title"] = "💾 Lokale Festplattensicherung",
                ["LocalBackup_Sub"] = "Automatische oder manuelle Sicherung auf der lokalen Festplatte. Die letzten 10 Sicherungen bleiben erhalten.",
                ["Backup_Now"] = "💾 Lokale Sicherung Erstellen",
                ["Restore_Backup"] = "📂 Aus Sicherung Wiederherstellen",
                ["JsonBackup_Title"] = "📤 JSON Export / Import",
                ["JsonBackup_Sub"] = "Exportieren oder importieren Sie Ihre Konfiguration als JSON-Datei.",
                ["Export"] = "📤 Exportieren (JSON)",
                ["Import"] = "📥 Importieren (JSON)",

                ["Tab5_Title"] = "Aktualisierungen & Diagnose",
                ["Tab5_Sub"] = "Systemdiagnoseprotokolle, Fehlerberichte und Updates.",
                ["Language"] = "🌐 Anzeigesprache",
                ["Language_Desc"] = "Wählen Sie Ihre bevorzugte Programmsprache.",
                ["Updates_Title"] = "🚀 Software-Updates",
                ["Installed_Version"] = "Installierte Version: v1.0.0",
                ["AutoCheck_Updates"] = "Beim Start automatisch nach Updates suchen",
                ["Check_Updates"] = "🔄 Jetzt Nach Updates Suchen",
                ["Diag_Title"] = "📊 Systemdiagnose & Protokolle",
                ["Diag_Sub"] = "Anwendungsprotokolle und Systemdiagnosedaten.",
                ["Open_Logs"] = "📁 Protokollordner Öffnen",
                ["Copy_Diag"] = "📋 Diagnose Kopieren",
                ["Reset_Title"] = "⚠️ Auf Werkseinstellungen Zurücksetzen",
                ["Reset_Sub"] = "Setzt Design- und Tastenkombinationen zurück (Benutzerdaten bleiben erhalten).",
                ["Reset_Factory"] = "Auf Werkseinstellungen Zurücksetzen",

                ["Status_Ready"] = "Bereit.",
                ["Status_Saved"] = "Einstellungen erfolgreich gespeichert.",
                ["Success"] = "Erfolg",
                ["Error"] = "Fehler",
                ["Restore_Success"] = "Sicherung erfolgreich wiederhergestellt.",
                ["Restore_Confirm"] = "Sicherung '{0}' wiederherstellen?\nAktuelle Daten werden überschrieben.",
                ["Restore_Confirm_Title"] = "Wiederherstellung Bestätigen",
                ["Reset_Confirm"] = "Alle Einstellungen auf Werkseinstellungen zurücksetzen?",
                ["Reset_Confirm_Title"] = "Einstellungen Zurücksetzen",
                ["Delete_Confirm"] = "'{0}' löschen?",
                ["Delete_Confirm_Title"] = "Löschen Bestätigen",

                ["Play"] = "▶ Spielen",
                ["Store"] = "🛒 Shop",
                ["Community"] = "👥 Gemeinschaft",
                ["Location"] = "📁 Ort",
                ["Run_Admin"] = "⚡ Als Admin Ausführen",
                ["Terminal"] = "⚡ Terminal",
                ["Open"] = "Öffnen",
                ["Copy"] = "Kopieren",
                ["Library"] = "Bibliothek",
                ["Launch"] = "Starten"
            };

            _translations["es"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Configuración y Gestión",
                ["Nav_Apps"] = "📋  Aplicaciones y Accesos",
                ["Nav_Themes"] = "🎨  Temas y Apariencia",
                ["Nav_Shortcuts"] = "⚙️  Atajos e Inicio",
                ["Nav_Backups"] = "💾  Copias de Seguridad",
                ["Nav_System"] = "ℹ️  Sistema y Diagnóstico",

                ["Tab1_Title"] = "Gestión de Aplicaciones y Accesos",
                ["Tab1_Sub"] = "Administre todos los programas, sitios web y carpetas del menú radial.",
                ["Scan_PC"] = "🔍 Escanear PC",
                ["Add_Item"] = "➕ Agregar Nuevo Elemento",
                ["Category"] = "Categoría:",
                ["All_Categories"] = "Todas las Categorías",
                ["Search"] = "Buscar:",
                ["Search_Placeholder"] = "Buscar aplicaciones, juegos, acciones...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Orden",
                ["Col_Icon"] = "Icono",
                ["Col_Name"] = "Nombre",
                ["Col_Type"] = "Tipo",
                ["Col_Category"] = "Categoría",
                ["Col_Launches"] = "Ejecuciones",
                ["Col_Target"] = "Destino",
                ["Col_Actions"] = "Acciones",

                ["Tab2_Title"] = "Temas y Personalización Visual",
                ["Tab2_Sub"] = "Seleccione entre 8 temas y ajuste la opacidad y densidad del menú radial.",
                ["Themes_Header"] = "Temas Seleccionados (8 Temas)",
                ["Preview_Header"] = "Vista Previa Radial en Vivo",
                ["Opacity_Title"] = "Opacidad del Menú Radial",
                ["Opacity_Desc"] = "Ajuste la transparencia del fondo de cristal.",
                ["Density_Title"] = "Modo de Densidad de Anillo",
                ["Density_Desc"] = "Número de elementos mostrados por página de anillo.",
                ["Density_Expanded"] = "Expandido (15 Elementos)",
                ["Density_Compact"] = "Compacto (18 Elementos)",
                ["Access_Title"] = "Accesibilidad y Rendimiento",
                ["Access_Sub"] = "Reduzca el movimiento para equipos con menos recursos.",
                ["Reduce_Motion"] = "Reducir Movimiento / Animaciones Simples",
                ["Palette_Title"] = "Paleta de Colores del Tema",
                ["Primary_Accent"] = "Acento Primario",
                ["Secondary_Accent"] = "Acento Secundario",
                ["Background"] = "Fondo",
                ["Icon_Bubble"] = "Burbuja de Icono",

                ["Tab3_Title"] = "Atajos de Activación e Inicio",
                ["Tab3_Sub"] = "Establezca los accesos de ratón y teclado para desplegar el menú.",
                ["Trigger_Title"] = "Atajo de Activación",
                ["Trigger_Desc"] = "Elija el botón del ratón o teclado para abrir el menú radial.",
                ["Assign_Shortcut"] = "🎯 Asignar Atajo Personalizado",
                ["Startup_Title"] = "Inicio de Windows",
                ["Startup_Check"] = "Iniciar automáticamente Radial Launcher en la bandeja al iniciar Windows",
                ["Behavior_Title"] = "🎯 Comportamiento y Reglas de Navegación",
                ["Behavior_Body"] = "• Cierre automático: El menú se cierra al alejar el cursor 330px.\n• Navegación global: Arrastre con el botón central o use la rueda del ratón.\n• Acciones rápidas: Pase el cursor sobre los elementos.",

                ["Tab4_Title"] = "Copias de Seguridad y Datos",
                ["Tab4_Sub"] = "Guarde y restaure sus accesos directos, estadísticas y temas de forma segura.",
                ["LocalBackup_Title"] = "💾 Copia de Seguridad en Disco Local",
                ["LocalBackup_Sub"] = "Copia automática o manual en almacenamiento local. Se conservan las últimas 10 copias.",
                ["Backup_Now"] = "💾 Crear Copia Local",
                ["Restore_Backup"] = "📂 Restaurar Copia",
                ["JsonBackup_Title"] = "📤 Exportar / Importar JSON",
                ["JsonBackup_Sub"] = "Exporte o importe su configuración completa en un archivo JSON.",
                ["Export"] = "📤 Exportar (JSON)",
                ["Import"] = "📥 Importar (JSON)",

                ["Tab5_Title"] = "Actualizaciones y Diagnóstico",
                ["Tab5_Sub"] = "Registros de diagnóstico del sistema, errores y actualizaciones.",
                ["Language"] = "🌐 Idioma de Visualización",
                ["Language_Desc"] = "Seleccione el idioma preferido para la interfaz.",
                ["Updates_Title"] = "🚀 Actualizaciones de Software",
                ["Installed_Version"] = "Versión Instalada: v1.0.0",
                ["AutoCheck_Updates"] = "Buscar actualizaciones automáticamente al iniciar",
                ["Check_Updates"] = "🔄 Buscar Actualizaciones",
                ["Diag_Title"] = "📊 Diagnóstico y Registros",
                ["Diag_Sub"] = "Registros de la aplicación e informe de diagnóstico.",
                ["Open_Logs"] = "📁 Abrir Carpeta de Registros",
                ["Copy_Diag"] = "📋 Copiar Diagnóstico",
                ["Reset_Title"] = "⚠️ Restablecer Valores de Fábrica",
                ["Reset_Sub"] = "Restaura ajustes visuales y atajos a sus valores por defecto.",
                ["Reset_Factory"] = "Restablecer Valores de Fábrica",

                ["Status_Ready"] = "Listo.",
                ["Status_Saved"] = "Configuración guardada con éxito.",
                ["Success"] = "Éxito",
                ["Error"] = "Error",
                ["Restore_Success"] = "Copia de seguridad restaurada correctamente.",
                ["Restore_Confirm"] = "¿Restaurar la copia '{0}'?\nSe sobrescribirán los datos actuales.",
                ["Restore_Confirm_Title"] = "Confirmar Restauración",
                ["Reset_Confirm"] = "¿Restablecer todos los ajustes a los valores iniciales?",
                ["Reset_Confirm_Title"] = "Restablecer Ajustes",
                ["Delete_Confirm"] = "¿Eliminar '{0}'?",
                ["Delete_Confirm_Title"] = "Confirmar Eliminación",

                ["Play"] = "▶ Jugar",
                ["Store"] = "🛒 Tienda",
                ["Community"] = "👥 Comunidad",
                ["Location"] = "📁 Ubicación",
                ["Run_Admin"] = "⚡ Ejecutar como Admin",
                ["Terminal"] = "⚡ Terminal",
                ["Open"] = "Abrir",
                ["Copy"] = "Copiar",
                ["Library"] = "Biblioteca",
                ["Launch"] = "Lanzar"
            };

            _translations["fr"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Paramètres & Gestion",
                ["Nav_Apps"] = "📋  Applications & Raccourcis",
                ["Nav_Themes"] = "🎨  Thèmes & Apparence",
                ["Nav_Shortcuts"] = "⚙️  Raccourcis & Démarrage",
                ["Nav_Backups"] = "💾  Sauvegarde & Données",
                ["Nav_System"] = "ℹ️  Système & Diagnostics",

                ["Tab1_Title"] = "Gestion des Applications & Raccourcis",
                ["Tab1_Sub"] = "Gérez tous les programmes, sites web et dossiers affichés dans le menu radial.",
                ["Scan_PC"] = "🔍 Analyser le PC",
                ["Add_Item"] = "➕ Ajouter un Élément",
                ["Category"] = "Catégorie :",
                ["All_Categories"] = "Toutes les catégories",
                ["Search"] = "Rechercher :",
                ["Search_Placeholder"] = "Rechercher des applications, jeux...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Ordre",
                ["Col_Icon"] = "Icône",
                ["Col_Name"] = "Nom",
                ["Col_Type"] = "Type",
                ["Col_Category"] = "Catégorie",
                ["Col_Launches"] = "Lancés",
                ["Col_Target"] = "Cible",
                ["Col_Actions"] = "Actions",

                ["Tab2_Title"] = "Thèmes & Personnalisation Visuelle",
                ["Tab2_Sub"] = "Choisissez parmi 8 thèmes et personnalisez l'opacité et la densité.",
                ["Themes_Header"] = "Thèmes Disponibles (8 Thèmes)",
                ["Preview_Header"] = "Aperçu Radial en Direct",
                ["Opacity_Title"] = "Opacité du Menu Radial",
                ["Opacity_Desc"] = "Réglez la transparence de l'arrière-plan.",
                ["Density_Title"] = "Densité de l'Anneau",
                ["Density_Desc"] = "Nombre d'éléments affichés par page d'anneau.",
                ["Density_Expanded"] = "Étendu (15 Éléments)",
                ["Density_Compact"] = "Compact (18 Éléments)",
                ["Access_Title"] = "Accessibilité & Performances",
                ["Access_Sub"] = "Réduisez les animations pour les ordinateurs peu puissants.",
                ["Reduce_Motion"] = "Réduire les Animations",
                ["Palette_Title"] = "Palette de Couleurs Active",
                ["Primary_Accent"] = "Accent Primaire",
                ["Secondary_Accent"] = "Accent Secondaire",
                ["Background"] = "Arrière-plan",
                ["Icon_Bubble"] = "Bulle d'Icône",

                ["Tab3_Title"] = "Raccourcis & Démarrage",
                ["Tab3_Sub"] = "Définissez le raccourci souris ou clavier pour ouvrir le menu.",
                ["Trigger_Title"] = "Raccourci d'Activation",
                ["Trigger_Desc"] = "Choisissez le bouton de souris ou le raccourci pour ouvrir le menu.",
                ["Assign_Shortcut"] = "🎯 Assigner un Raccourci",
                ["Startup_Title"] = "Démarrage Windows",
                ["Startup_Check"] = "Lancer automatiquement Radial Launcher au démarrage de Windows",
                ["Behavior_Title"] = "🎯 Comportement & Navigation",
                ["Behavior_Body"] = "• Fermeture automatique : Le menu se ferme au-delà de 330px.\n• Navigation : Glisser avec le bouton du milieu ou molette.\n• Actions rapides : Survolez les éléments pour afficher leurs actions.",

                ["Tab4_Title"] = "Sauvegarde & Données",
                ["Tab4_Sub"] = "Sauvegardez vos raccourcis, statistiques et paramètres.",
                ["LocalBackup_Title"] = "💾 Sauvegarde sur Disque Local",
                ["LocalBackup_Sub"] = "Sauvegarde automatique ou manuelle en local. Les 10 dernières sauvegardes sont conservées.",
                ["Backup_Now"] = "💾 Créer une Sauvegarde",
                ["Restore_Backup"] = "📂 Restaurer une Sauvegarde",
                ["JsonBackup_Title"] = "📤 Exportation / Importation JSON",
                ["JsonBackup_Sub"] = "Exportez ou importez votre configuration complète sous forme de fichier JSON.",
                ["Export"] = "📤 Exporter (JSON)",
                ["Import"] = "📥 Importer (JSON)",

                ["Tab5_Title"] = "Mises à Jour & Diagnostics",
                ["Tab5_Sub"] = "Journaux de diagnostic, rapports d'erreurs et mises à jour logicielles.",
                ["Language"] = "🌐 Langue d'Affichage",
                ["Language_Desc"] = "Sélectionnez votre langue d'interface préférée.",
                ["Updates_Title"] = "🚀 Mises à Jour du Logiciel",
                ["Installed_Version"] = "Version Installée : v1.0.0",
                ["AutoCheck_Updates"] = "Vérifier automatiquement les mises à jour au démarrage",
                ["Check_Updates"] = "🔄 Vérifier les Mises à Jour",
                ["Diag_Title"] = "📊 Diagnostics & Journaux Système",
                ["Diag_Sub"] = "Journaux de l'application et diagnostic système.",
                ["Open_Logs"] = "📁 Ouvrir le Dossier des Journaux",
                ["Copy_Diag"] = "📋 Copier les Diagnostics",
                ["Reset_Title"] = "⚠️ Réinitialiser aux Paramètres d'Usine",
                ["Reset_Sub"] = "Restaure les paramètres visuels et raccourcis par défaut.",
                ["Reset_Factory"] = "Réinitialiser aux Paramètres d'Usine",

                ["Status_Ready"] = "Prêt.",
                ["Status_Saved"] = "Paramètres enregistrés avec succès.",
                ["Success"] = "Succès",
                ["Error"] = "Erreur",
                ["Restore_Success"] = "Sauvegarde restaurée avec succès.",
                ["Restore_Confirm"] = "Restaurer la sauvegarde '{0}' ?\nLes données actuelles seront écrasées.",
                ["Restore_Confirm_Title"] = "Confirmation de Restauration",
                ["Reset_Confirm"] = "Réinitialiser tous les paramètres aux valeurs d'usine ?",
                ["Reset_Confirm_Title"] = "Réinitialiser les Paramètres",
                ["Delete_Confirm"] = "Supprimer '{0}' ?",
                ["Delete_Confirm_Title"] = "Confirmation de Suppression",

                ["Play"] = "▶ Jouer",
                ["Store"] = "🛒 Boutique",
                ["Community"] = "👥 Communauté",
                ["Location"] = "📁 Emplacement",
                ["Run_Admin"] = "⚡ Exécuter en Admin",
                ["Terminal"] = "⚡ Terminal",
                ["Open"] = "Ouvrir",
                ["Copy"] = "Copier",
                ["Library"] = "Bibliothèque",
                ["Launch"] = "Lancer"
            };

            _translations["it"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Impostazioni e Gestione",
                ["Nav_Apps"] = "📋  Applicazioni e Scorciatoie",
                ["Nav_Themes"] = "🎨  Temi e Aspetto",
                ["Nav_Shortcuts"] = "⚙️  Scorciatoie e Avvio",
                ["Nav_Backups"] = "💾  Backup e Dati",
                ["Nav_System"] = "ℹ️  Sistema e Diagnostica",

                ["Tab1_Title"] = "Gestione Applicazioni & Scorciatoie",
                ["Tab1_Sub"] = "Gestisci tutte le app, giochi, siti e cartelle nel menu radiale.",
                ["Scan_PC"] = "🔍 Scansiona PC",
                ["Add_Item"] = "➕ Aggiungi Elemento",
                ["Category"] = "Categoria:",
                ["All_Categories"] = "Tutte le Categorie",
                ["Search"] = "Cerca:",
                ["Search_Placeholder"] = "Cerca app, giochi, azioni...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Ord",
                ["Col_Icon"] = "Icona",
                ["Col_Name"] = "Nome",
                ["Col_Type"] = "Tipo",
                ["Col_Category"] = "Categoria",
                ["Col_Launches"] = "Avvii",
                ["Col_Target"] = "Destinazione",
                ["Col_Actions"] = "Azioni",

                ["Tab2_Title"] = "Temi e Personalizzazione Visiva",
                ["Tab2_Sub"] = "Scegli tra 8 temi curati e personalizza opacità e densità.",
                ["Themes_Header"] = "Temi Disponibili (8 Temi)",
                ["Preview_Header"] = "Anteprima Radiale dal Vivo",
                ["Opacity_Title"] = "Opacità Menu Radiale",
                ["Opacity_Desc"] = "Regola il livello di trasparenza dello sfondo.",
                ["Density_Title"] = "Densità dell'Anello",
                ["Density_Desc"] = "Numero di elementi mostrati per pagina.",
                ["Density_Expanded"] = "Espanso (15 Elementi)",
                ["Density_Compact"] = "Compatto (18 Elementi)",
                ["Access_Title"] = "Accessibilità e Prestazioni",
                ["Access_Sub"] = "Riduci le animazioni per sistemi a basse prestazioni.",
                ["Reduce_Motion"] = "Riduci Movimento",
                ["Palette_Title"] = "Tavolozza Colori del Tema",
                ["Primary_Accent"] = "Accento Primario",
                ["Secondary_Accent"] = "Accento Secondario",
                ["Background"] = "Sfondo",
                ["Icon_Bubble"] = "Bolla Icona",

                ["Tab3_Title"] = "Scorciatoie di Attivazione e Avvio",
                ["Tab3_Sub"] = "Imposta pulsante mouse o tastiera per aprire il menu radiale.",
                ["Trigger_Title"] = "Scorciatoia di Attivazione",
                ["Trigger_Desc"] = "Scegli il pulsante del mouse o la scorciatoia da tastiera.",
                ["Assign_Shortcut"] = "🎯 Assegna Scorciatoia Personalizzata",
                ["Startup_Title"] = "Avvio di Windows",
                ["Startup_Check"] = "Avvia automaticamente Radial Launcher nella barra delle applicazioni all'avvio",
                ["Behavior_Title"] = "🎯 Comportamento e Regole di Navigazione",
                ["Behavior_Body"] = "• Chiusura automatica: Il menu si chiude a 330px di distanza.\n• Navigazione: Trascina con il tasto centrale o usa la rotellina.\n• Azioni rapide: Passa il mouse sugli elementi.",

                ["Tab4_Title"] = "Backup e Gestione Dati",
                ["Tab4_Sub"] = "Salva e ripristina in sicurezza scorciatoie e impostazioni.",
                ["LocalBackup_Title"] = "💾 Backup su Disco Locale",
                ["LocalBackup_Sub"] = "Backup automatico o manuale sul disco locale. Gli ultimi 10 backup vengono conservati.",
                ["Backup_Now"] = "💾 Crea Backup Locale",
                ["Restore_Backup"] = "📂 Ripristina Backup",
                ["JsonBackup_Title"] = "📤 Esporta / Importa JSON",
                ["JsonBackup_Sub"] = "Esporta o importa la tua configurazione completa in formato JSON.",
                ["Export"] = "📤 Esporta (JSON)",
                ["Import"] = "📥 Importa (JSON)",

                ["Tab5_Title"] = "Aggiornamenti e Diagnostica",
                ["Tab5_Sub"] = "Registri di sistema, log degli errori e aggiornamenti software.",
                ["Language"] = "🌐 Lingua di Visualizzazione",
                ["Language_Desc"] = "Seleziona la lingua per l'interfaccia.",
                ["Updates_Title"] = "🚀 Aggiornamenti Software",
                ["Installed_Version"] = "Versione Installata: v1.0.0",
                ["AutoCheck_Updates"] = "Controlla aggiornamenti all'avvio",
                ["Check_Updates"] = "🔄 Controlla Aggiornamenti",
                ["Diag_Title"] = "📊 Diagnostica e Registri",
                ["Diag_Sub"] = "Log dell'applicazione e diagnostica.",
                ["Open_Logs"] = "📁 Apri Cartella Log",
                ["Copy_Diag"] = "📋 Copia Diagnostica",
                ["Reset_Title"] = "⚠️ Ripristina Impostazioni di Fabbrica",
                ["Reset_Sub"] = "Ripristina tutte le impostazioni visive e scorciatoie ai valori predefiniti.",
                ["Reset_Factory"] = "Ripristina Impostazioni di Fabbrica",

                ["Status_Ready"] = "Pronto.",
                ["Status_Saved"] = "Impostazioni salvate con successo.",
                ["Success"] = "Successo",
                ["Error"] = "Errore",
                ["Restore_Success"] = "Backup ripristinato con successo.",
                ["Restore_Confirm"] = "Ripristinare il backup '{0}'?\nI dati correnti verranno sovrascritti.",
                ["Restore_Confirm_Title"] = "Conferma Ripristino",
                ["Reset_Confirm"] = "Ripristinare tutte le impostazioni ai valori iniziali?",
                ["Reset_Confirm_Title"] = "Ripristina Impostazioni",
                ["Delete_Confirm"] = "Eliminare '{0}'?",
                ["Delete_Confirm_Title"] = "Conferma Eliminazione",

                ["Play"] = "▶ Gioca",
                ["Store"] = "🛒 Negozio",
                ["Community"] = "👥 Comunità",
                ["Location"] = "📁 Posizione",
                ["Run_Admin"] = "⚡ Esegui come Admin",
                ["Terminal"] = "⚡ Terminale",
                ["Open"] = "Apri",
                ["Copy"] = "Copia",
                ["Library"] = "Libreria",
                ["Launch"] = "Avvia"
            };

            _translations["ja"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — 設定と管理",
                ["Nav_Apps"] = "📋  アプリとショートカット",
                ["Nav_Themes"] = "🎨  テーマと外観",
                ["Nav_Shortcuts"] = "⚙️  ショートカットとスタートアップ",
                ["Nav_Backups"] = "💾  バックアップとデータ",
                ["Nav_System"] = "ℹ️  システムと診断",

                ["Tab1_Title"] = "アプリケーション＆ショートカット管理",
                ["Tab1_Sub"] = "ラジアルメニューに登録されているすべてのアイテムを管理します。",
                ["Scan_PC"] = "🔍 PCをスキャン",
                ["Add_Item"] = "➕ 新規アイテム追加",
                ["Category"] = "カテゴリ:",
                ["All_Categories"] = "すべてのカテゴリ",
                ["Search"] = "検索:",
                ["Search_Placeholder"] = "アプリ、ゲーム、アクションを検索...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "順序",
                ["Col_Icon"] = "アイコン",
                ["Col_Name"] = "名前",
                ["Col_Type"] = "種類",
                ["Col_Category"] = "カテゴリ",
                ["Col_Launches"] = "起動回数",
                ["Col_Target"] = "ターゲット",
                ["Col_Actions"] = "操作",

                ["Tab2_Title"] = "テーマとデザイン設定",
                ["Tab2_Sub"] = "8つの洗練されたテーマから選択し、不透明度と密度を調整します。",
                ["Themes_Header"] = "厳選テーマ (8テーマ)",
                ["Preview_Header"] = "リアルタイム円形プレビュー",
                ["Opacity_Title"] = "メニューの不透明度",
                ["Opacity_Desc"] = "円形メニューの背景の透明度を調整します。",
                ["Density_Title"] = "リング密度モード",
                ["Density_Desc"] = "1ページあたりに配置するアイテム数。",
                ["Density_Expanded"] = "標準 (15 アイテム)",
                ["Density_Compact"] = "コンパクト (18 アイテム)",
                ["Access_Title"] = "アクセシビリティとパフォーマンス",
                ["Access_Sub"] = "低スペック環境やシンプルな表示のためにアニメーションを抑えます。",
                ["Reduce_Motion"] = "アニメーションを簡略化",
                ["Palette_Title"] = "テーマのカラーパレット",
                ["Primary_Accent"] = "プライマリアクセント",
                ["Secondary_Accent"] = "セカンダリアクセント",
                ["Background"] = "背景",
                ["Icon_Bubble"] = "アイコンバブル",

                ["Tab3_Title"] = "起動ショートカットとスタートアップ",
                ["Tab3_Sub"] = "メニューを表示するためのマウスボタンやキーボードショートカットを設定します。",
                ["Trigger_Title"] = "起動ショートカット",
                ["Trigger_Desc"] = "ラジアルメニューを開くマウスまたはキーボードを選択します。",
                ["Assign_Shortcut"] = "🎯 カスタムショートカット割り当て",
                ["Startup_Title"] = "Windows スタートアップ",
                ["Startup_Check"] = "Windows起動時にトレイで自動起動する",
                ["Behavior_Title"] = "🎯 メニュー動作と操作ガイド",
                ["Behavior_Body"] = "• 自動終了: マウスが330px以上離れると自動で閉じます。\n• ページ移動: 中ボタンドラッグまたはホイールで切替可能です。\n• クイック操作: アイテムにマウスを重ねると中心にアクションを表示します。",

                ["Tab4_Title"] = "バックアップとデータ管理",
                ["Tab4_Sub"] = "ショートカットやテーマ設定を安全にバックアップ・復元します。",
                ["LocalBackup_Title"] = "💾 ローカルディスクバックアップ",
                ["LocalBackup_Sub"] = "ローカルストレージへ自動または手動でバックアップ。最新10件が安全に保存されます。",
                ["Backup_Now"] = "💾 ローカルバックアップ作成",
                ["Restore_Backup"] = "📂 バックアップから復元",
                ["JsonBackup_Title"] = "📤 JSON エクスポート / インポート",
                ["JsonBackup_Sub"] = "設定とアイテムをJSONファイルとして保存または読み込みます。",
                ["Export"] = "📤 エクスポート (JSON)",
                ["Import"] = "📥 インポート (JSON)",

                ["Tab5_Title"] = "アップデートと診断情報",
                ["Tab5_Sub"] = "システムログ、診断情報およびソフトウェア更新。",
                ["Language"] = "🌐 表示言語",
                ["Language_Desc"] = "Radial Launcherの表示言語を選択します。",
                ["Updates_Title"] = "🚀 ソフトウェアアップデート",
                ["Installed_Version"] = "インストール済みバージョン: v1.0.0",
                ["AutoCheck_Updates"] = "起動時に自動でアップデートを確認する",
                ["Check_Updates"] = "🔄 アップデートを確認",
                ["Diag_Title"] = "📊 システム診断とログ",
                ["Diag_Sub"] = "アプリケーションログと診断情報。",
                ["Open_Logs"] = "📁 ログフォルダを開く",
                ["Copy_Diag"] = "📋 診断情報をコピー",
                ["Reset_Title"] = "⚠️ 初期設定にリセット",
                ["Reset_Sub"] = "テーマやショートカットを初期状態に戻します（ユーザーアイテムは保持されます）。",
                ["Reset_Factory"] = "初期設定にリセット",

                ["Status_Ready"] = "準備完了。",
                ["Status_Saved"] = "設定が正常に保存されました。",
                ["Success"] = "成功",
                ["Error"] = "エラー",
                ["Restore_Success"] = "バックアップが正常に復元されました。",
                ["Restore_Confirm"] = "バックアップ '{0}' を復元しますか？\n現在の設定が上書きされます。",
                ["Restore_Confirm_Title"] = "復元の確認",
                ["Reset_Confirm"] = "すべての設定を初期状態にリセットしますか？",
                ["Reset_Confirm_Title"] = "設定のリセット",
                ["Delete_Confirm"] = "'{0}' を削除しますか？",
                ["Delete_Confirm_Title"] = "削除の確認",

                ["Play"] = "▶ プレイ",
                ["Store"] = "🛒 ストア",
                ["Community"] = "👥 コミュニティ",
                ["Location"] = "📁 場所",
                ["Run_Admin"] = "⚡ 管理者として実行",
                ["Terminal"] = "⚡ ターミナル",
                ["Open"] = "開く",
                ["Copy"] = "コピー",
                ["Library"] = "ライブラリ",
                ["Launch"] = "起動"
            };

            _translations["ko"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — 설정 및 관리",
                ["Nav_Apps"] = "📋  앱 및 바로가기",
                ["Nav_Themes"] = "🎨  테마 및 디자인",
                ["Nav_Shortcuts"] = "⚙️  단축키 및 시작 프로그램",
                ["Nav_Backups"] = "💾  백업 및 데이터",
                ["Nav_System"] = "ℹ️  시스템 및 진단",

                ["Tab1_Title"] = "애플리케이션 및 바로가기 관리",
                ["Tab1_Sub"] = "원형 메뉴에 등록된 모든 앱, 게임, 웹사이트 및 폴더를 관리합니다.",
                ["Scan_PC"] = "🔍 PC 검사",
                ["Add_Item"] = "➕ 새 항목 추가",
                ["Category"] = "카테고리:",
                ["All_Categories"] = "전체 카테고리",
                ["Search"] = "검색:",
                ["Search_Placeholder"] = "앱, 게임, 작업 검색...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "순서",
                ["Col_Icon"] = "아이콘",
                ["Col_Name"] = "이름",
                ["Col_Type"] = "유형",
                ["Col_Category"] = "카테고리",
                ["Col_Launches"] = "실행 횟수",
                ["Col_Target"] = "대상",
                ["Col_Actions"] = "작업",

                ["Tab2_Title"] = "시각 테마 및 투명도 설정",
                ["Tab2_Sub"] = "8가지 테마 중 선택하고 투명도와 밀도를 조정하세요.",
                ["Themes_Header"] = "테마 목록 (8가지 테마)",
                ["Preview_Header"] = "실시간 원형 미리보기",
                ["Opacity_Title"] = "메뉴 불투명도",
                ["Opacity_Desc"] = "배경 유리 투명도를 조절합니다.",
                ["Density_Title"] = "원형 밀도 모드",
                ["Density_Desc"] = "한 페이지에 표시할 항목 수를 설정합니다.",
                ["Density_Expanded"] = "확장 (15개 항목)",
                ["Density_Compact"] = "컴팩트 (18개 항목)",
                ["Access_Title"] = "접근성 및 성능",
                ["Access_Sub"] = "저사양 시스템을 위해 애니메이션 효과를 줄입니다.",
                ["Reduce_Motion"] = "동작 줄이기",
                ["Palette_Title"] = "테마 색상 팔레트",
                ["Primary_Accent"] = "기본 강조색",
                ["Secondary_Accent"] = "보조 강조색",
                ["Background"] = "배경색",
                ["Icon_Bubble"] = "아이콘 버블",

                ["Tab3_Title"] = "실행 단축키 및 시작 프로그램",
                ["Tab3_Sub"] = "메뉴를 열 마우스 버튼 또는 키보드 단축키를 설정하세요.",
                ["Trigger_Title"] = "실행 단축키",
                ["Trigger_Desc"] = "원형 메뉴를 열 마우스 버튼 또는 키보드 단축키를 선택하세요.",
                ["Assign_Shortcut"] = "🎯 사용자 지정 단축키 할당",
                ["Startup_Title"] = "Windows 시작 프로그램",
                ["Startup_Check"] = "Windows 시작 시 트레이 모드로 자동 실행",
                ["Behavior_Title"] = "🎯 메뉴 동작 및 탐색 안내",
                ["Behavior_Body"] = "• 자동 닫기: 마우스가 330px 이상 벗어나면 자동으로 닫힙니다.\n• 페이지 이동: 마우스 휠 또는 휠 버튼 드래그로 전환합니다.\n• 빠른 작업: 항목 위에 마우스를 올리면 중앙에 작업 카드가 표시됩니다.",

                ["Tab4_Title"] = "백업 및 데이터 관리",
                ["Tab4_Sub"] = "바로가기와 테마 설정을 안전하게 백업 및 복원합니다.",
                ["LocalBackup_Title"] = "💾 로컬 디스크 백업 및 복원",
                ["LocalBackup_Sub"] = "로컬 디스크에 자동 또는 수동으로 백업합니다. 최근 10개의 백업이 안전하게 유지됩니다.",
                ["Backup_Now"] = "💾 로컬 백업 생성",
                ["Restore_Backup"] = "📂 백업에서 복원",
                ["JsonBackup_Title"] = "📤 JSON 내보내기 / 가져오기",
                ["JsonBackup_Sub"] = "모든 설정과 바로가기를 JSON 파일로 저장하거나 가져옵니다.",
                ["Export"] = "📤 내보내기 (JSON)",
                ["Import"] = "📥 가져오기 (JSON)",

                ["Tab5_Title"] = "업데이트 및 진단",
                ["Tab5_Sub"] = "시스템 진단 로그, 오류 기록 및 소프트웨어 업데이트.",
                ["Language"] = "🌐 표시 언어",
                ["Language_Desc"] = "기본 표시 언어를 선택합니다.",
                ["Updates_Title"] = "🚀 소프트웨어 업데이트",
                ["Installed_Version"] = "설치된 버전: v1.0.0",
                ["AutoCheck_Updates"] = "시작 시 자동으로 업데이트 확인",
                ["Check_Updates"] = "🔄 지금 업데이트 확인",
                ["Diag_Title"] = "📊 시스템 진단 및 로그",
                ["Diag_Sub"] = "애플리케이션 로그 및 진단 정보 요약.",
                ["Open_Logs"] = "📁 로그 폴더 열기",
                ["Copy_Diag"] = "📋 진단 정보 복사",
                ["Reset_Title"] = "⚠️ 초기 설정으로 복원",
                ["Reset_Sub"] = "모든 시각 설정 및 단축키를 기본값으로 되돌립니다 (사용자 항목 보존).",
                ["Reset_Factory"] = "초기 설정으로 복원",

                ["Status_Ready"] = "준비 완료.",
                ["Status_Saved"] = "설정이 성공적으로 저장되었습니다.",
                ["Success"] = "성공",
                ["Error"] = "오류",
                ["Restore_Success"] = "백업이 성공적으로 복원되었습니다.",
                ["Restore_Confirm"] = "'{0}' 백업을 복원하시겠습니까?\n현재 데이터가 덮어씌워집니다.",
                ["Restore_Confirm_Title"] = "복원 확인",
                ["Reset_Confirm"] = "모든 설정을 기본값으로 초기화하시겠습니까?",
                ["Reset_Confirm_Title"] = "설정 초기화",
                ["Delete_Confirm"] = "'{0}' 항목을 삭제하시겠습니까?",
                ["Delete_Confirm_Title"] = "삭제 확인",

                ["Play"] = "▶ 플레이",
                ["Store"] = "🛒 상점",
                ["Community"] = "👥 커뮤니티",
                ["Location"] = "📁 위치",
                ["Run_Admin"] = "⚡ 관리자 권한 실행",
                ["Terminal"] = "⚡ 터미널",
                ["Open"] = "열기",
                ["Copy"] = "복사",
                ["Library"] = "라이브러리",
                ["Launch"] = "실행"
            };

            _translations["pl"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Ustawienia i Zarządzanie",
                ["Nav_Apps"] = "📋  Aplikacje i Skróty",
                ["Nav_Themes"] = "🎨  Motywy i Wygląd",
                ["Nav_Shortcuts"] = "⚙️  Skróty i Autostart",
                ["Nav_Backups"] = "💾  Kopia Zapasowa i Dane",
                ["Nav_System"] = "ℹ️  System i Diagnostyka",

                ["Tab1_Title"] = "Zarządzanie Aplikacjami i Skrótami",
                ["Tab1_Sub"] = "Zarządzaj programami, grami i folderami w menu kołowym.",
                ["Scan_PC"] = "🔍 Skanuj Komputer",
                ["Add_Item"] = "➕ Dodaj Nowy Element",
                ["Category"] = "Kategoria:",
                ["All_Categories"] = "Wszystkie Kategorie",
                ["Search"] = "Szukaj:",
                ["Search_Placeholder"] = "Szukaj aplikacji, gier...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Poz",
                ["Col_Icon"] = "Ikona",
                ["Col_Name"] = "Nazwa",
                ["Col_Type"] = "Typ",
                ["Col_Category"] = "Kategoria",
                ["Col_Launches"] = "Uruchomienia",
                ["Col_Target"] = "Cel",
                ["Col_Actions"] = "Działania",

                ["Tab2_Title"] = "Motywy i Wygląd",
                ["Tab2_Sub"] = "Wybierz spośród 8 motywów i dostosuj przezroczystość.",
                ["Themes_Header"] = "Dostępne Motywy (8 Motywów)",
                ["Preview_Header"] = "Podgląd Menu na Żywo",
                ["Opacity_Title"] = "Przezroczystość Menu",
                ["Opacity_Desc"] = "Dostosuj poziom przezroczystości tła.",
                ["Density_Title"] = "Gęstość Pierścienia",
                ["Density_Desc"] = "Liczba elementów na stronę pierścienia.",
                ["Density_Expanded"] = "Rozszerzony (15 Elementów)",
                ["Density_Compact"] = "Kompaktowy (18 Elementów)",
                ["Access_Title"] = "Dostępność i Wydajność",
                ["Access_Sub"] = "Zredukuj animacje na słabszych urządzeniach.",
                ["Reduce_Motion"] = "Zredukuj Ruch",
                ["Palette_Title"] = "Paleta Kolorów Motywu",
                ["Primary_Accent"] = "Główny Akcent",
                ["Secondary_Accent"] = "Drugi Akcent",
                ["Background"] = "Tło",
                ["Icon_Bubble"] = "Bąbel Ikony",

                ["Tab3_Title"] = "Skróty Aktywacji i Autostart",
                ["Tab3_Sub"] = "Ustaw przycisk myszy lub skrót klawiszowy do otwierania menu.",
                ["Trigger_Title"] = "Skrót Aktywacji",
                ["Trigger_Desc"] = "Wybierz przycisk myszy lub skrót klawiszowy.",
                ["Assign_Shortcut"] = "🎯 Przypisz Nowy Skrót",
                ["Startup_Title"] = "Autostart Windows",
                ["Startup_Check"] = "Uruchamiaj Radial Launcher automatycznie w zasobniku systemowym",
                ["Behavior_Title"] = "🎯 Zachowanie Menu i Nawigacja",
                ["Behavior_Body"] = "• Automatyczne zamykanie: Menu zamyka się po oddaleniu o 330px.\n• Nawigacja: Przeciągnij środkowym przyciskiem lub użyj kółka.\n• Szybkie akcje: Najedź na element, aby zobaczyć opcje.",

                ["Tab4_Title"] = "Kopie Zapasowe i Dane",
                ["Tab4_Sub"] = "Bezpiecznie twórz i przywracaj kopie zapasowe.",
                ["LocalBackup_Title"] = "💾 Kopia Zapasowa na Dysku Lokalnym",
                ["LocalBackup_Sub"] = "Automatyczna lub ręczna kopia zapasowa na dysku lokalnym. Ostatnie 10 kopii jest zachowywanych.",
                ["Backup_Now"] = "💾 Utwórz Kopię Zapasową",
                ["Restore_Backup"] = "📂 Przywróć z Kopii",
                ["JsonBackup_Title"] = "📤 Eksport / Import JSON",
                ["JsonBackup_Sub"] = "Eksportuj lub importuj konfigurację jako plik JSON.",
                ["Export"] = "📤 Eksportuj (JSON)",
                ["Import"] = "📥 Importuj (JSON)",

                ["Tab5_Title"] = "Aktualizacje i Diagnostyka",
                ["Tab5_Sub"] = "Dzienniki systemowe, błędy i aktualizacje oprogramowania.",
                ["Language"] = "🌐 Język Interfejsu",
                ["Language_Desc"] = "Wybierz preferowany język interfejsu.",
                ["Updates_Title"] = "🚀 Aktualizacje Oprogramowania",
                ["Installed_Version"] = "Zainstalowana Wersja: v1.0.0",
                ["AutoCheck_Updates"] = "Automatycznie sprawdzaj aktualizacje przy uruchomieniu",
                ["Check_Updates"] = "🔄 Sprawdź Aktualizacje",
                ["Diag_Title"] = "📊 Diagnostyka i Dzienniki",
                ["Diag_Sub"] = "Dzienniki aplikacji i informacje diagnostyczne.",
                ["Open_Logs"] = "📁 Otwórz Folder Dzienników",
                ["Copy_Diag"] = "📋 Kopiuj Diagnostykę",
                ["Reset_Title"] = "⚠️ Przywróć Ustawienia Fabryczne",
                ["Reset_Sub"] = "Przywraca ustawienia wyglądu i skrótów do wartości fabrycznych.",
                ["Reset_Factory"] = "Przywróć Ustawienia Fabryczne",

                ["Status_Ready"] = "Gotowy.",
                ["Status_Saved"] = "Ustawienia zapisane pomyślnie.",
                ["Success"] = "Sukces",
                ["Error"] = "Błąd",
                ["Restore_Success"] = "Kopia zapasowa została pomyślnie przywrócona.",
                ["Restore_Confirm"] = "Przywrócić kopię '{0}'?\nBieżące dane zostaną nadpisane.",
                ["Restore_Confirm_Title"] = "Potwierdzenie Przywracania",
                ["Reset_Confirm"] = "Przywrócić wszystkie ustawienia do wartości domyślnych?",
                ["Reset_Confirm_Title"] = "Reset Ustawień",
                ["Delete_Confirm"] = "Usunąć '{0}'?",
                ["Delete_Confirm_Title"] = "Potwierdzenie Usunięcia",

                ["Play"] = "▶ Graj",
                ["Store"] = "🛒 Sklep",
                ["Community"] = "👥 Społeczność",
                ["Location"] = "📁 Lokalizacja",
                ["Run_Admin"] = "⚡ Uruchom jako Administrator",
                ["Terminal"] = "⚡ Terminal",
                ["Open"] = "Otwórz",
                ["Copy"] = "Kopiuj",
                ["Library"] = "Biblioteka",
                ["Launch"] = "Uruchom"
            };

            _translations["pt-BR"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Configurações e Gerenciamento",
                ["Nav_Apps"] = "📋  Aplicativos e Atalhos",
                ["Nav_Themes"] = "🎨  Temas e Aparência",
                ["Nav_Shortcuts"] = "⚙️  Atalhos e Inicialização",
                ["Nav_Backups"] = "💾  Backup e Dados",
                ["Nav_System"] = "ℹ️  Sistema e Diagnósticos",

                ["Tab1_Title"] = "Gerenciamento de Aplicativos e Atalhos",
                ["Tab1_Sub"] = "Gerencie todos os aplicativos, jogos e pastas do menu radial.",
                ["Scan_PC"] = "🔍 Escanear PC",
                ["Add_Item"] = "➕ Adicionar Novo Item",
                ["Category"] = "Categoria:",
                ["All_Categories"] = "Todas as Categorias",
                ["Search"] = "Pesquisar:",
                ["Search_Placeholder"] = "Pesquisar aplicativos, jogos, ações...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "Ordem",
                ["Col_Icon"] = "Ícone",
                ["Col_Name"] = "Nome",
                ["Col_Type"] = "Tipo",
                ["Col_Category"] = "Categoria",
                ["Col_Launches"] = "Execuções",
                ["Col_Target"] = "Destino",
                ["Col_Actions"] = "Ações",

                ["Tab2_Title"] = "Temas e Personalização Visual",
                ["Tab2_Sub"] = "Escolha entre 8 temas e personalize opacidade e densidade.",
                ["Themes_Header"] = "Temas Selecionados (8 Temas)",
                ["Preview_Header"] = "Visualização Radial ao Vivo",
                ["Opacity_Title"] = "Opacidade do Menu Radial",
                ["Opacity_Desc"] = "Ajuste o nível de transparência do fundo de vidro.",
                ["Density_Title"] = "Densidade do Anel",
                ["Density_Desc"] = "Número de itens exibidos por página.",
                ["Density_Expanded"] = "Expandido (15 Itens)",
                ["Density_Compact"] = "Compacto (18 Itens)",
                ["Access_Title"] = "Acessibilidade e Desempenho",
                ["Access_Sub"] = "Reduza animações para computadores mais modestos.",
                ["Reduce_Motion"] = "Reduzir Movimento",
                ["Palette_Title"] = "Paleta de Cores do Tema",
                ["Primary_Accent"] = "Destaque Primário",
                ["Secondary_Accent"] = "Destaque Secundário",
                ["Background"] = "Fundo",
                ["Icon_Bubble"] = "Bolha de Ícone",

                ["Tab3_Title"] = "Atalhos de Ativação e Inicialização",
                ["Tab3_Sub"] = "Defina o botão do mouse ou atalho de teclado para abrir o menu.",
                ["Trigger_Title"] = "Atalho de Ativação",
                ["Trigger_Desc"] = "Escolha o botão do mouse ou atalho de teclado para abrir o menu.",
                ["Assign_Shortcut"] = "🎯 Atribuir Novo Atalho",
                ["Startup_Title"] = "Inicialização do Windows",
                ["Startup_Check"] = "Iniciar automaticamente o Radial Launcher na bandeja com o Windows",
                ["Behavior_Title"] = "🎯 Comportamento e Regras de Navegação",
                ["Behavior_Body"] = "• Fechamento automático: O menu fecha ao afastar o cursor 330px.\n• Navegação global: Arraste com o botão do meio ou use a roda do mouse.\n• Ações rápidas: Passe o cursor sobre os itens para ações instantâneas.",

                ["Tab4_Title"] = "Backup e Gerenciamento de Dados",
                ["Tab4_Sub"] = "Salve e restaure seus atalhos e configurações com segurança.",
                ["LocalBackup_Title"] = "💾 Backup no Disco Local",
                ["LocalBackup_Sub"] = "Backup automático ou manual no armazenamento local. Os últimos 10 backups são mantidos.",
                ["Backup_Now"] = "💾 Criar Backup Local",
                ["Restore_Backup"] = "📂 Restaurar do Backup",
                ["JsonBackup_Title"] = "📤 Exportar / Importar JSON",
                ["JsonBackup_Sub"] = "Exporte ou importe sua configuração completa em arquivo JSON.",
                ["Export"] = "📤 Exportar (JSON)",
                ["Import"] = "📥 Importar (JSON)",

                ["Tab5_Title"] = "Atualizações e Diagnósticos",
                ["Tab5_Sub"] = "Logs de diagnóstico, relatórios de erros e atualizações de software.",
                ["Language"] = "🌐 Idioma de Exibição",
                ["Language_Desc"] = "Selecione o idioma de sua preferência.",
                ["Updates_Title"] = "🚀 Atualizações de Software",
                ["Installed_Version"] = "Versão Instalada: v1.0.0",
                ["AutoCheck_Updates"] = "Verificar atualizações automaticamente ao iniciar",
                ["Check_Updates"] = "🔄 Verificar Atualizações",
                ["Diag_Title"] = "📊 Diagnóstico e Logs do Sistema",
                ["Diag_Sub"] = "Logs do aplicativo e resumo do diagnóstico.",
                ["Open_Logs"] = "📁 Abrir Pasta de Logs",
                ["Copy_Diag"] = "📋 Copiar Diagnóstico",
                ["Reset_Title"] = "⚠️ Restaurar Padrões de Fábrica",
                ["Reset_Sub"] = "Restaura configurações visuais e atalhos aos padrões de fábrica.",
                ["Reset_Factory"] = "Restaurar Padrões de Fábrica",

                ["Status_Ready"] = "Pronto.",
                ["Status_Saved"] = "Configurações salvas com sucesso.",
                ["Success"] = "Sucesso",
                ["Error"] = "Erro",
                ["Restore_Success"] = "Backup restaurado com sucesso.",
                ["Restore_Confirm"] = "Restaurar o backup '{0}'?\nOs dados atuais serão substituídos.",
                ["Restore_Confirm_Title"] = "Confirmar Restauração",
                ["Reset_Confirm"] = "Restaurar todas as configurações para os padrões de fábrica?",
                ["Reset_Confirm_Title"] = "Redefinir Configurações",
                ["Delete_Confirm"] = "Excluir '{0}'?",
                ["Delete_Confirm_Title"] = "Confirmar Exclusão",

                ["Play"] = "▶ Jogar",
                ["Store"] = "🛒 Loja",
                ["Community"] = "👥 Comunidade",
                ["Location"] = "📁 Localização",
                ["Run_Admin"] = "⚡ Executar como Administrador",
                ["Terminal"] = "⚡ Terminal",
                ["Open"] = "Abrir",
                ["Copy"] = "Copiar",
                ["Library"] = "Biblioteca",
                ["Launch"] = "Iniciar"
            };

            _translations["ru"] = new Dictionary<string, string>
            {
                ["App_Title"] = "Radial Launcher — Настройки и Управление",
                ["Nav_Apps"] = "📋  Приложения и Ярлыки",
                ["Nav_Themes"] = "🎨  Темы и Внешний Вид",
                ["Nav_Shortcuts"] = "⚙️  Горячие Клавиши и Автозапуск",
                ["Nav_Backups"] = "💾  Резервные Копии и Данные",
                ["Nav_System"] = "ℹ️  Система и Диагностика",

                ["Tab1_Title"] = "Управление Приложениями и Ярлыками",
                ["Tab1_Sub"] = "Управляйте всеми программами, играми и папками в радиальном меню.",
                ["Scan_PC"] = "🔍 Сканировать ПК",
                ["Add_Item"] = "➕ Добавить Элемент",
                ["Category"] = "Категория:",
                ["All_Categories"] = "Все Категории",
                ["Search"] = "Поиск:",
                ["Search_Placeholder"] = "Поиск приложений, игр, действий...",
                ["Col_Star"] = "⭐",
                ["Col_Order"] = "№",
                ["Col_Icon"] = "Значок",
                ["Col_Name"] = "Имя",
                ["Col_Type"] = "Тип",
                ["Col_Category"] = "Категория",
                ["Col_Launches"] = "Запуски",
                ["Col_Target"] = "Путь",
                ["Col_Actions"] = "Действия",

                ["Tab2_Title"] = "Темы и Настройка Внешнего Вида",
                ["Tab2_Sub"] = "Выберите из 8 тем и настройте прозрачность и плотность меню.",
                ["Themes_Header"] = "Доступные Темы (8 Тем)",
                ["Preview_Header"] = "Живой Просмотр Меню",
                ["Opacity_Title"] = "Прозрачность Меню",
                ["Opacity_Desc"] = "Настройте уровень прозрачности фона.",
                ["Density_Title"] = "Плотность Кольца",
                ["Density_Desc"] = "Количество элементов на одной странице кольца.",
                ["Density_Expanded"] = "Расширенный (15 Элементов)",
                ["Density_Compact"] = "Компактный (18 Элементов)",
                ["Access_Title"] = "Специальные Возможности",
                ["Access_Sub"] = "Упростите анимацию для слабых ПК.",
                ["Reduce_Motion"] = "Упростить Анимации",
                ["Palette_Title"] = "Палитра Цветов Темы",
                ["Primary_Accent"] = "Основной Акцент",
                ["Secondary_Accent"] = "Дополнительный Акцент",
                ["Background"] = "Фон",
                ["Icon_Bubble"] = "Пузырек Иконки",

                ["Tab3_Title"] = "Клавиши Активации и Автозапуск",
                ["Tab3_Sub"] = "Назначьте кнопку мыши или сочетание клавиш для вызова меню.",
                ["Trigger_Title"] = "Клавиша Активации",
                ["Trigger_Desc"] = "Выберите кнопку мыши или клавиатуры для вызова меню.",
                ["Assign_Shortcut"] = "🎯 Назначить Свою Клавишу",
                ["Startup_Title"] = "Автозапуск Windows",
                ["Startup_Check"] = "Запускать Radial Launcher в трее при старте Windows",
                ["Behavior_Title"] = "🎯 Поведение Меню и Навигация",
                ["Behavior_Body"] = "• Автозакрытие: Меню закрывается при удалении курсора на 330px.\n• Навигация: Перетаскивание средней кнопкой мыши или колесо.\n• Быстрые действия: Наведение курсора на значок открывает действия.",

                ["Tab4_Title"] = "Резервное Копирование и Данные",
                ["Tab4_Sub"] = "Надежно сохраняйте и восстанавливайте настройки и ярлыки.",
                ["LocalBackup_Title"] = "💾 Локальная Резервная Копия",
                ["LocalBackup_Sub"] = "Автоматическое или ручное резервное копирование на локальный диск. Хранятся последние 10 копий.",
                ["Backup_Now"] = "💾 Создать Резервную Копию",
                ["Restore_Backup"] = "📂 Восстановить из Копии",
                ["JsonBackup_Title"] = "📤 Экспорт / Импорт JSON",
                ["JsonBackup_Sub"] = "Экспортируйте или импортируйте конфигурацию в виде файла JSON.",
                ["Export"] = "📤 Экспорт (JSON)",
                ["Import"] = "📥 Импорт (JSON)",

                ["Tab5_Title"] = "Обновления и Диагностика",
                ["Tab5_Sub"] = "Журналы диагностики, отчеты об ошибках и обновления ПО.",
                ["Language"] = "🌐 Язык Интерфейса",
                ["Language_Desc"] = "Выберите предпочитаемый язык интерфейса.",
                ["Updates_Title"] = "🚀 Обновления Программы",
                ["Installed_Version"] = "Установленная Версия: v1.0.0",
                ["AutoCheck_Updates"] = "Автоматически проверять обновления при запуске",
                ["Check_Updates"] = "🔄 Проверить Обновления",
                ["Diag_Title"] = "📊 Диагностика и Логи",
                ["Diag_Sub"] = "Журналы приложения и диагностический отчет.",
                ["Open_Logs"] = "📁 Открыть Папку Логов",
                ["Copy_Diag"] = "📋 Копировать Диагностику",
                ["Reset_Title"] = "⚠️ Сбросить к Заводским Настройкам",
                ["Reset_Sub"] = "Сбрасывает все визуальные настройки и горячие клавиши к заводским значениям.",
                ["Reset_Factory"] = "Сбросить к Заводским Настройкам",

                ["Status_Ready"] = "Готово.",
                ["Status_Saved"] = "Настройки успешно сохранены.",
                ["Success"] = "Успешно",
                ["Error"] = "Ошибка",
                ["Restore_Success"] = "Резервная копия успешно восстановлена.",
                ["Restore_Confirm"] = "Восстановить резервную копию '{0}'?\nТекущие данные будут перезаписаны.",
                ["Restore_Confirm_Title"] = "Подтверждение Восстановления",
                ["Reset_Confirm"] = "Сбросить все настройки к начальным значениям?",
                ["Reset_Confirm_Title"] = "Сброс Настроек",
                ["Delete_Confirm"] = "Удалить '{0}'?",
                ["Delete_Confirm_Title"] = "Подтверждение Удаления",

                ["Play"] = "▶ Играть",
                ["Store"] = "🛒 Магазин",
                ["Community"] = "👥 Сообщество",
                ["Location"] = "📁 Расположение",
                ["Run_Admin"] = "⚡ Запуск от Имени Администратора",
                ["Terminal"] = "⚡ Терминал",
                ["Open"] = "Открыть",
                ["Copy"] = "Копировать",
                ["Library"] = "Библиотека",
                ["Launch"] = "Запуск"
            };
        }
    }
}

