<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>

    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <Product>Radial Launcher Setup</Product>
    <Title>Radial Launcher Setup Wizard</Title>
    <Company>Radial Launcher Team</Company>
    <Authors>Radial Launcher Team</Authors>
    <Description>Standalone Installer for Radial Launcher</Description>
    <Copyright>Copyright © 2026 Radial Launcher Team</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" />
  </ItemGroup>

</Project>
